# Copyright (c) 2012 Rich Porter - see LICENSE for further details

.PHONY : all clean

all :
	$(MAKE) -C ../c
	$(MAKE) -C ../python
	$(MAKE) -C ../verilog

clean :
	$(MAKE) -C ../c       clean
	$(MAKE) -C ../python  clean
	$(MAKE) -C ../verilog clean
