#!/bin/bash
# Copyright (c) 2012, 2013 Rich Porter - see LICENSE for further details

function urlget {
  test -e $1 || wget --no-check-certificate $2 -O $1 || exit
}

root=`dirname $0`

urlget $root/bottle.py                 https://raw.github.com/defnull/bottle/master/bottle.py
urlget $root/static/jquery.dynatree.js http://dynatree.googlecode.com/svn/trunk/src/jquery.dynatree.js
urlget $root/static/ui.dynatree.css    http://dynatree.googlecode.com/svn/trunk/src/skin/ui.dynatree.css
urlget $root/static/icons-rtl.gif      http://dynatree.googlecode.com/svn/trunk/src/skin/icons-rtl.gif  
urlget $root/static/icons.gif          http://dynatree.googlecode.com/svn/trunk/src/skin/icons.gif      
urlget $root/static/loading.gif        http://dynatree.googlecode.com/svn/trunk/src/skin/loading.gif    
urlget $root/static/vline-rtl.gif      http://dynatree.googlecode.com/svn/trunk/src/skin/vline-rtl.gif  
urlget $root/static/vline.gif          http://dynatree.googlecode.com/svn/trunk/src/skin/vline.gif      
urlget $root/static/jquery.dataTables.js http://www.datatables.net/download/build/jquery.dataTables.js

LD_LIBRARY_PATH=$root/../python:$LD_LIBRARY_PATH \
PYTHONPATH=.:$root/../python:$PYTHONPATH \
exec python $0.py --root=$root "$@"
