#!/bin/bash
# Copyright (c) 2012, 2013 Rich Porter - see LICENSE for further details

function urlget {
  test -e $1 || wget --no-check-certificate $2 -O $1 || exit
}

root=`dirname $0`

urlget $root/bottle.py https://raw.github.com/defnull/bottle/master/bottle.py

LD_LIBRARY_PATH=$root/../python:$LD_LIBRARY_PATH PYTHONPATH=.:$root/../python:$PYTHONPATH exec python $0.py --root=$root "$@"
