#!/bin/sh

# Copyright (c) 2012 Rich Porter - see LICENSE for further details

root=`dirname $0`

bottle=$root/bottle.py
test -e $bottle || wget --no-check-certificate https://raw.github.com/defnull/bottle/master/bottle.py -O $bottle

LD_LIBRARY_PATH=$root/../python:$LD_LIBRARY_PATH PYTHONPATH=.:$root/../python:$PYTHONPATH exec python $0.py --root=$root "$@"
